SELECT KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME AS "KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME
ORDER BY "GMV_SUM" DESC
LIMIT 50000;

SELECT KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME AS "KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME
ORDER BY "GMV_SUM" DESC
LIMIT 50000;

SELECT SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL AS "SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL
ORDER BY "GMV_SUM" DESC
LIMIT 50000;

SELECT CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE) AS "__timestamp",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE)
ORDER BY "GMV_SUM" DESC
LIMIT 50000;

SELECT CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE) AS "__timestamp",
       COUNT (1) AS "TRANS_CNT"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE)
ORDER BY "TRANS_CNT" DESC
LIMIT 50000;

SELECT CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE) AS "__timestamp",
       sum(KYLIN_SALES.PRICE)/count(distinct KYLIN_SALES.SELLER_ID) AS "PER_CAPITA_SALES"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE)
ORDER BY "PER_CAPITA_SALES" DESC
LIMIT 50000;

SELECT SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL AS "SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL
ORDER BY "GMV_SUM" DESC
LIMIT 10000;

SELECT CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE) AS "__timestamp",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM",
           COUNT (1) AS "TRANS_CNT"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY CAST(FLOOR(CAST(KYLIN_CAL_DT.MONTH_BEG_DT AS TIMESTAMP) TO MONTH) AS DATE)
ORDER BY "GMV_SUM" DESC
LIMIT 50000;

SELECT KYLIN_SALES.LSTG_FORMAT_NAME AS "KYLIN_SALES.LSTG_FORMAT_NAME",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY KYLIN_SALES.LSTG_FORMAT_NAME
ORDER BY "GMV_SUM" DESC
LIMIT 10000;

SELECT BUYER_COUNTRY.NAME AS "BUYER_COUNTRY.NAME",
       SUM (SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL) AS "SELLER_LEVEL_SUM",
           SUM (KYLIN_SALES.PRICE) AS "GMV_SUM",
               COUNT (1) AS "TRANS_CNT"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY BUYER_COUNTRY.NAME
ORDER BY "SELLER_LEVEL_SUM" DESC;

SELECT BUYER_COUNTRY.NAME AS "BUYER_COUNTRY.NAME",
       KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME AS "KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME",
       KYLIN_SALES.LSTG_FORMAT_NAME AS "KYLIN_SALES.LSTG_FORMAT_NAME",
       KYLIN_SALES.BUYER_ID AS "KYLIN_SALES.BUYER_ID",
       SUM (KYLIN_SALES.PRICE) AS "GMV_SUM"
FROM "DEFAULT"."KYLIN_SALES" AS "KYLIN_SALES"
JOIN "DEFAULT"."KYLIN_CAL_DT" AS "KYLIN_CAL_DT" ON KYLIN_SALES.PART_DT = KYLIN_CAL_DT.CAL_DT
JOIN "DEFAULT"."KYLIN_CATEGORY_GROUPINGS" AS "KYLIN_CATEGORY_GROUPINGS" ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
AND KYLIN_SALES.LSTG_SITE_ID = KYLIN_CATEGORY_GROUPINGS.SITE_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "BUYER_ACCOUNT" ON KYLIN_SALES.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_ACCOUNT" AS "SELLER_ACCOUNT" ON KYLIN_SALES.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "BUYER_COUNTRY" ON BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
JOIN "DEFAULT"."KYLIN_COUNTRY" AS "SELLER_COUNTRY" ON SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY
WHERE KYLIN_CAL_DT.MONTH_BEG_DT >= CAST('2012-01-01' AS DATE)
  AND KYLIN_CAL_DT.MONTH_BEG_DT <= CAST('2013-12-31' AS DATE)
  AND KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME IN ('Collectibles')
  AND KYLIN_CATEGORY_GROUPINGS.CATEG_LVL3_NAME IN ('Decorative Collectible Brands')
  AND SELLER_ACCOUNT.ACCOUNT_SELLER_LEVEL IN (1)
GROUP BY BUYER_COUNTRY.NAME,
         KYLIN_CATEGORY_GROUPINGS.META_CATEG_NAME,
         KYLIN_SALES.LSTG_FORMAT_NAME,
         KYLIN_SALES.BUYER_ID
ORDER BY "GMV_SUM" DESC
LIMIT 1000;
